### ISSUE TITLE
Deployment of tutorial fails

### ISSUE THREAD

**Issue by qbzzt** [ethereum-optimism/optimism-tutorial#30]
**Describe the bug**

`yarn install` fails with this error:

```
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "ethereum-waffle > @ethereum-waffle/compiler > typechain > ts-essentials@6.0.7" has unmet peer dependency "typescript@>=3.7.0".
warning " > hardhat-deploy@0.7.5" has unmet peer dependency "@ethersproject/hardware-wallets@^5.0.14".

[4/4] Building fresh packages...
Done in 75.79s.
```

And afterwards you can't progress because `npx hardhat <anything>` also fails:

```
An unexpected error occurred:

Error: Cannot find module '@eth-optimism/hardhat-ovm'
Require stack:
- /home/qbzzt1/optimism-tutorial/hardhat.config.js
- /home/qbzzt1/optimism-tutorial/node_modules/hardhat/internal/core/config/config-loading.js
- /home/qbzzt1/optimism-tutorial/node_modules/hardhat/internal/cli/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/qbzzt1/optimism-tutorial/hardhat.config.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/qbzzt1/optimism-tutorial/hardhat.config.js',
    '/home/qbzzt1/optimism-tutorial/node_modules/hardhat/internal/core/config/config-loading.js',
    '/home/qbzzt1/optimism-tutorial/node_modules/hardhat/internal/cli/cli.js'
  ]
}
```

**To Reproduce**

1. Create a Debian VM on GCP
2. Connect to that VM
3. `git clone https://github.com/ethereum-optimism/optimism-tutorial`
4. `cd optimism-tutorial`
5. `yarn install`

**Expected behavior**

The expected behavior is for the HardHat build process to succeed

**System Specs:**
 - OS: `Linux optimism 4.19.0-16-cloud-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux`
 - Nodejs: 14.16.1
 - Yarn: 1.22.10

**Comment by qbzzt** [comment]
> Should be fixed now. Sorry about that!

No problem, thank you for the quick reply. I had one other road block, which I fixed with the pull request I submitted.
