### ISSUE TITLE
Error: call revert exception

### ISSUE THREAD

**Issue by mistricky** [ethereum-optimism/optimism-tutorial#63]
**Describe the bug**
I have attempted at the `l1-l2-deposit-withdrawal` example, but I get the following error when I run the `scripts/example.js` by harhat.

```
Error: call revert exception (method="getAddress(string)", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.4.0)
    at Logger.makeError (/Users/zhanhaozhao/Documents/repositories/optimism-tutorial/l1-l2-deposit-withdrawal/node_modules/@ethersproject/logger/src.ts/index.ts:213:28)
    at Logger.throwError (/Users/zhanhaozhao/Documents/repositories/optimism-tutorial/l1-l2-deposit-withdrawal/node_modules/@ethersproject/logger/src.ts/index.ts:225:20)
    at Interface.decodeFunctionResult (/Users/zhanhaozhao/Documents/repositories/optimism-tutorial/l1-l2-deposit-withdrawal/node_modules/@ethersproject/abi/src.ts/interface.ts:425:23)
    at Contract.<anonymous> (/Users/zhanhaozhao/Documents/repositories/optimism-tutorial/l1-l2-deposit-withdrawal/node_modules/@ethersproject/contracts/src.ts/index.ts:332:44)
    at step (/Users/zhanhaozhao/Documents/repositories/optimism-tutorial/l1-l2-deposit-withdrawal/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/Users/zhanhaozhao/Documents/repositories/optimism-tutorial/l1-l2-deposit-withdrawal/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/Users/zhanhaozhao/Documents/repositories/optimism-tutorial/l1-l2-deposit-withdrawal/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'getAddress(string)',
  errorArgs: null,
  errorName: null,
  errorSignature: null,
  address: '0x4200000000000000000000000000000000000008',
  args: [ 'OVM_L1CrossDomainMessenger' ],
  transaction: {
    data: '0xbf40fac10000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001a4f564d5f4c3143726f7373446f6d61696e4d657373656e676572000000000000',
    to: '0x4200000000000000000000000000000000000008'
  }
}
```

Did I miss something? 🤔️

**To Reproduce**
1. cd the `l1-l2-deposit-withdrawal` & install dependencies
2. `npx hardhat node`
3. `npx hardhat run ./scripts/example.js --network localhost`

**Expected behavior**
No error and working fine.

**Comment by elenadimitrova** [comment]
I tested this example today and it does work for me. 
I suspect it is failing for you as you are explicitly running against a `localhost` network which isn't defined in the tutorial. Please follow the guide on starting your own dev node https://community.optimism.io/docs/developers/l2/dev-node.html followed by the steps in the Readme https://github.com/ethereum-optimism/optimism-tutorial/tree/main/l1-l2-deposit-withdrawal#readme
Reopen if still an issue for you.
